##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## Makefile
##

SRC = my_compute_power_rec.c \
      my_compute_square_root.c \
      my_find_prime_sup.c \
      my_getnbr.c \
      my_isalpha.c \
      my_isdigit.c \
      my_isneg.c \
      my_is_prime.c \
      my_putchar.c \
      my_putnbr.c \
      my_putstr.c \
      my_revstr.c \
      my_showmem.c \
      my_showstr.c \
      my_sort_int_array.c \
      my_strcapitalize.c \
      my_strcat.c \
      my_strcmp.c \
      my_strcpy.c \
      my_strdup.c \
      my_str_isalpha.c \
      my_str_islower.c \
      my_str_isnum.c \
      my_str_isprintable.c \
      my_str_isupper.c \
      my_strlen.c \
      my_strlowcase.c \
      my_strncat.c \
      my_strncmp.c \
      my_strncpy.c \
      my_strstr.c \
      my_strupcase.c \
      my_swap.c \
      my_put_unsigned_nbr.c \
      my_put_octal.c \
      my_put_float.c \
      my_put_hexa.c \
      my_put_pointer.c \
      my_put_e.c \
      my_put_g.c \
      my_put_signed_long.c \
      my_put_signed_longlong.c \
      my_put_unsigned_long.c \
      my_put_unsigned_longlong.c \
      my_str_to_int.c \
      find_nbr.c \
      count_int.c \
      my_put_minus.c \
      my_put_plus.c \
      my_put_zero.c \
      case_e.c \
      case_fi.c \
      case_g.c \
      case_l.c \
      case_minus.c \
      case_ou.c \
      case_p.c \
      case_plus.c \
      case_pourcent.c \
      case_sd.c \
      case_x.c \
      case_zero.c \
      count_int.c \
      my_charlowcase.c \
      my_sort_str_array.c \
      my_rev_array.c \
      my_int_to_str.c \
      my_arraylen.c \
      count_lines_columns.c \
      replace_and_display.c \
      checking_map.c \
      display_perm.c \
      add_arguments.c \

OBJ = $(SRC:.c=.o)

NAME = libmy.a

all: build

build:        $(OBJ)
	ar rc ../../$(NAME) $(OBJ)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f ../../$(NAME)
